name: Remo
options:
  bundleIdPrefix: com.hippogriff.remo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

packages:
  RemoModels:
    path: Packages/RemoModels
  RemoNetworking:
    path: Packages/RemoNetworking
  RemoPhotoUpload:
    path: Packages/RemoPhotoUpload
  RemoChatUI:
    path: Packages/RemoChatUI
  RemoAnnotation:
    path: Packages/RemoAnnotation
  RemoDesignViews:
    path: Packages/RemoDesignViews
  RemoShoppingList:
    path: Packages/RemoShoppingList
  RemoLiDAR:
    path: Packages/RemoLiDAR

targets:
  Remo:
    type: application
    platform: iOS
    sources:
      - Remo
    dependencies:
      - package: RemoModels
      - package: RemoNetworking
      - package: RemoPhotoUpload
      - package: RemoChatUI
      - package: RemoAnnotation
      - package: RemoDesignViews
      - package: RemoShoppingList
      - package: RemoLiDAR
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hippogriff.remo
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: Remo/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    info:
      path: Remo/Info.plist
      properties:
        CFBundleDisplayName: Remo
        CFBundleName: Remo
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: "Remo needs camera access to photograph your room."
        NSPhotoLibraryUsageDescription: "Remo needs photo library access to select room and inspiration photos."
